env:
  es6: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
globals:
  CalendarApp: readonly
  GoogleAppsScript: readonly
  SpreadsheetApp: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2019
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/indent':
    - error
    - 2
  '@typescript-eslint/explicit-function-return-type':
    - warn
    - allowExpressions: true
  '@typescript-eslint/member-delimiter-style':
    - error
    - multiline:
        delimiter: comma
        requireLast: false
      singleline:
        delimiter: comma
        requireLast: false
  '@typescript-eslint/semi':
    - error
    - never

overrides:
  - files:
      - webpack.*.js
    env:
      amd: true
      es6: true
      node: true
    rules:
      '@typescript-eslint/camelcase': off
      '@typescript-eslint/no-var-requires': off
